# Generated by Django 3.1.5 on 2021-01-29 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcuser',
            name='usernmae',
            field=models.CharField(max_length=32, verbose_name='사용자명'),
        ),
    ]
