# Generated by Django 3.1.5 on 2021-01-29 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0002_auto_20210129_1025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fcuser',
            options={'verbose_name': '패스트캠퍼스 사용자', 'verbose_name_plural': '패스트캠퍼스 사용자'},
        ),
        migrations.RenameField(
            model_name='fcuser',
            old_name='usernmae',
            new_name='username',
        ),
    ]
