# Generated by Django 3.1.5 on 2021-01-31 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0003_auto_20210129_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcuser',
            name='usereamil',
            field=models.EmailField(default='test@gmail.com', max_length=128, verbose_name='사용자 이메일'),
            preserve_default=False,
        ),
    ]
